[package]
name = "ero-blockwheel"
version = "0.1.31"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Persistent binary blocks with rotating wheel like access."
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git" }

log = "^0.4"
serde = "^1.0"
futures = "^0.3"
bincode = "^1.2"
serde_derive = "^1.0"

tokio = { version = "^0.2", features = ["full"] }
