[package]
name = "ero-blockwheel-fs"
version = "0.11.2"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Persistent binary blocks with rotating wheel like access."
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git" }
o1 = { git = "https://github.com/swizard0/o1.git" }
alloc-pool = { git = "https://github.com/swizard0/alloc-pool.git" }

log = "^0.4"
crc = "^1.8"
serde = "^1.0"
rayon = "^1.5"
futures = "^0.3"
bincode = "^1.3"
serde_derive = "^1.0"

tokio = { version = "^1.0", features = ["full"] }

[dev-dependencies]
rand = "^0.7"
