[package]
name = "stress"
version = "0.1.0"
authors = ["Alexey Voznyuk <me@swizard.info>"]
description = "Stress test utility for ero-blockwheel library."
edition = "2018"

[dependencies]
ero = { git = "https://github.com/swizard0/ero.git" }
ero-blockwheel = { path = "../.." }

log = "^0.4"
clap = "^2.33"
structopt = "^0.2"
pretty_env_logger = "^0.4"
tokio = { version = "0.2", features = ["full"] }
